const Whiskey = [
  { nameofArray: "Whiskey" },
  {
    title: "Jack Daniel's Old N.7",
    title_az: "Jack Daniel's Old N.7",
    price: "8.00 / 120.00 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Jack Daniel's Tennessee Apple",
    title_az: "Jack Daniel's Tennessee Apple",
    price: "8 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Jack Daniel's Tennessee Honey",
    title_az: "Jack Daniel's Tennessee Honey",
    price: "8 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Jack Daniel's Gentleman Jack",
    title_az: "Jack Daniel's Gentleman Jack",
    price: "10 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Woodford Reserve",
    title_az: "Woodford Reserve",
    price: "10 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Chivas Regal 12 Y.O.",
    title_az: "Chivas Regal 12 İllik",
    price: "9 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Chivas Regal 18 Y.O.",
    title_az: "Chivas Regal 18 İllik",
    price: "14 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Glenfiddich 12 Y.O.",
    title_az: "Glenfiddich 12 İllik",
    price: "11 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Singleton",
    title_az: "Singleton",
    price: "9 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Jameson",
    title_az: "Jameson",
    price: "8.00 / 120.00 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "JW Black Label",
    title_az: "JW Black Label",
    price: "8 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "JW Red Label",
    title_az: "JW Red Label",
    price: "7 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Jim Beam",
    title_az: "Jim Beam",
    price: "7 AZN",
    desc_az: "",
    desc_eng: "",
  },
];

const Tequila = [
  { nameofArray: "Tequila" },
  {
    title: "Sierra",
    title_az: "Sierra",
    price: "6 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Olmeca Blanco",
    title_az: "Olmeca Blanco",
    price: "6 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Olmeca Gold",
    title_az: "Olmeca Gold",
    price: "7 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Patron",
    title_az: "Patron",
    price: "12 AZN",
    desc_az: "",
    desc_eng: "",
  },
];

const Aperitif = [
  { nameofArray: "Aperitif" },
  {
    title: "Aperol",
    title_az: "Aperol",
    price: "8 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Campari",
    title_az: "Campari",
    price: "8 AZN",
    desc_az: "",
    desc_eng: "",
  },
];

const Gin = [
  { nameofArray: "Gin" },
  {
    title: "Gin Mare",
    title_az: "Gin Mare",
    price: "10 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Gordon's",
    title_az: "Gordon's",
    price: "7 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Bombay Sapphire",
    title_az: "Bombay Sapphire",
    price: "9 AZN",
    desc_az: "",
    desc_eng: "",
  },
];

const Liqueur = [
  { nameofArray: "Liqueur" },
  {
    title: "Jagermeister",
    title_az: "Jagermeister",
    price: "6 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Baileys",
    title_az: "Baileys",
    price: "8 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Cointreau",
    title_az: "Cointreau",
    price: "8 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Amaretto",
    title_az: "Amaretto",
    price: "8 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Kahlua",
    title_az: "Kahlua",
    price: "8 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Sambuca",
    title_az: "Sambuca",
    price: "10 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Xenta Absenta",
    title_az: "Xenta Absenta",
    price: "10 AZN",
    desc_az: "",
    desc_eng: "",
  },
];

const Vermouth = [
  { nameofArray: "Vermouth" },
  {
    title: "Martini Fiero",
    title_az: "Martini Fiero",
    price: "8 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Martini Bianco",
    title_az: "Martini Bianco",
    price: "8 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Martini Rosato",
    title_az: "Martini Rosato",
    price: "8 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Martini Rosso",
    title_az: "Martini Rosso",
    price: "8 AZN",
    desc_az: "",
    desc_eng: "",
  },
];

const Vodka = [
  { nameofArray: "Vodka" },
  {
    title: "Nemiroff",
    title_az: "Nemiroff",
    price: "5.00 / 70.00 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Absolut",
    title_az: "Absolut",
    price: "6.00 / 90.00 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Finlandia",
    title_az: "Finlandia",
    price: "6.00 / 90.00 AZN",
    desc_az: "",
    desc_eng: "",
  },
];

const Rum = [
  { nameofArray: "Rums" },
  {
    title: "Captain Morgan Gold",
    title_az: "Captain Morgan Gold",
    price: "7 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Captain Morgan Jamaica",
    title_az: "Captain Morgan Jamaica",
    price: "7 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Bacardi",
    title_az: "Bacardi",
    price: "7 AZN",
    desc_az: "",
    desc_eng: "",
  },
];

const BEERS = [
  { nameofArray: "Beers" },
  {
    title: "Blanc Kronenburg",
    title_az: "Blanc Kronenburg",
    price: "7 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Xirdalan Draft (filtered)",
    title_az: "Xirdalan Çəkmə (Filtrli)",
    price: "4.5 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Xirdalan Draft (unfiltered)",
    title_az: "Xirdalan Çəkmə (Filtrsiz)",
    price: "5 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Xirdalan Bottle",
    title_az: "Xirdalan Şüşə",
    price: "6 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Guinness",
    title_az: "Guinness",
    price: "10 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Erdinger",
    title_az: "Erdinger",
    price: "9 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Corona",
    title_az: "Corona",
    price: "8 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Heineken",
    title_az: "Heineken",
    price: "8 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Tuborg",
    title_az: "Tuborg",
    price: "7 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Efes Draft",
    title_az: "Efes Çəkmə",
    price: "7 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Efes Zero",
    title_az: "Efes Zero",
    price: "6 AZN",
    desc_az: "",
    desc_eng: "",
  },
];

const SOFTS = [
  { nameofArray: "Soft Drinks" },
  {
    title: "Redbull",
    title_az: "Redbull",
    price: "6 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Tonic",
    title_az: "Tonic",
    price: "6 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Coca Cola",
    title_az: "Coca Cola",
    price: "5 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Juice / Fresh Juice",
    title_az: "Şirə / Təzə Şirə",
    price: "4.00 / 8.00 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Ice Tea",
    title_az: "Soyuq Çay",
    price: "5 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Water / Su",
    title_az: "Su",
    price: "3 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Tea / Çay",
    title_az: "Çay",
    price: "5 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Espresso",
    title_az: "Espresso",
    price: "5 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Americano",
    title_az: "Americano",
    price: "6 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Cappuccino",
    title_az: "Cappuccino",
    price: "7 AZN",
    desc_az: "",
    desc_eng: "",
  },
];

const Wines = [
  { nameofArray: "Wines" },
  {
    title: "Meysari Maxxani Premium (Red dry)",
    title_az: "Meysari Maxxani Premium (Qırmızı quru)",
    price: "39.9 AZN",
    desc_az: "Qırmızı quru şərab, premium",
    desc_eng: "red dry wine, premium",
  },
  {
    title: "Meysari Marcan (Red dry)",
    title_az: "Meysari Marcan (Qırmızı quru)",
    price: "34.9 AZN",
    desc_az: "Qırmızı quru şərab",
    desc_eng: "red dry wine",
  },
  {
    title: "Meysari Safdar (White dry)",
    title_az: "Meysari Safdar (Ağ quru)",
    price: "34.9 AZN",
    desc_az: "Ağ quru şərab",
    desc_eng: "white dry wine",
  },
  {
    title: "Meysari Sanam (Rose dry)",
    title_az: "Meysari Sanam (Çəhrayı quru)",
    price: "34.9 AZN",
    desc_az: "Çəhrayı quru şərab",
    desc_eng: "rose dry wine",
  },
  {
    title: "Chabiant (Red dry)",
    title_az: "Chabiant (Qırmızı quru)",
    price: "6/26 AZN",
    desc_az: "Qırmızı quru şərab",
    desc_eng: "red dry wine",
  },
  {
    title: "Chabiant (White dry)",
    title_az: "Chabiant (Ağ quru)",
    price: "6/26 AZN",
    desc_az: "Ağ quru şərab",
    desc_eng: "white dry wine",
  },
  {
    title: "Chabiant Saperavi - Cabernet sauvignon",
    title_az: "Chabiant Saperavi - Cabernet sauvignon",
    price: "39.9 AZN",
    desc_az: "Saperavi və Cabernet sauvignon qarışıq şərabı",
    desc_eng: "Saperavi and Cabernet Sauvignon blend wine",
  },
  {
    title: "Chabiant Vino Nuovo",
    title_az: "Chabiant Vino Nuovo",
    price: "39.9 AZN",
    desc_az: "Yeni şərab, qırmızı",
    desc_eng: "new wine, red",
  },
  {
    title: "Savalan Merlot (Red semi)",
    title_az: "Savalan Merlot (Qırmızı semi)",
    price: "6/28 AZN",
    desc_az: "Qırmızı semi şərab, Merlot",
    desc_eng: "red semi wine, Merlot",
  },
  {
    title: "Savalan Merlot (Red dry)",
    title_az: "Savalan Merlot (Qırmızı quru)",
    price: "6/28 AZN",
    desc_az: "Qırmızı quru şərab, Merlot",
    desc_eng: "red dry wine, Merlot",
  },
  {
    title: "Hillside Prestige (White Dry)",
    title_az: "Hillside Prestige (Ağ quru)",
    price: "6/28 AZN",
    desc_az: "Ağ quru şərab, premium",
    desc_eng: "white dry wine, premium",
  },
  {
    title: "Hillside Curve (Red dry)",
    title_az: "Hillside Curve (Qırmızı quru)",
    price: "6/28 AZN",
    desc_az: "Qırmızı quru şərab",
    desc_eng: "red dry wine",
  },
  {
    title: "Hillside Prestige (Rose Dry)",
    title_az: "Hillside Prestige (Çəhrayı quru)",
    price: "28 AZN",
    desc_az: "Çəhrayı quru şərab, premium",
    desc_eng: "rose dry wine, premium",
  },
  {
    title: "Aggo Red (Pomegranate)",
    title_az: "Aggo Qırmızı (Nar)",
    price: "4/16 AZN",
    desc_az: "Nar əsasında hazırlanmış qırmızı şərab",
    desc_eng: "pomegranate-based red wine",
  },
  {
    title: "Sangria Premium",
    title_az: "Sangria Premium",
    price: "6/16 AZN",
    desc_az: "Premium sangria, meyveli karışım",
    desc_eng: "premium sangria, fruity mix",
  },
];

const Prosecco = [
  { nameofArray: "Prosecco or Sparkling Wines" },
  {
    title: "Astoria",
    title_az: "Astoria",
    price: "65 AZN",
    desc_az: "İtalyan köpüklü şərab, premium",
    desc_eng: "Italian sparkling wine, premium",
  },
  {
    title: "Cinzano",
    title_az: "Cinzano",
    price: "70 AZN",
    desc_az: "İtalyan köpüklü şərab, premium",
    desc_eng: "Italian sparkling wine, premium",
  },
];

const Coktails = [
  { nameofArray: "Cocktails" },
  {
    title: "Aperol Spritz",
    title_az: "Aperol Spritz",
    price: "15 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Long Island (cola/energy drink)",
    title_az: "Long Island (kola/enerji içkisi)",
    price: "15.00 / 17.00 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Martini Tonic",
    title_az: "Martini Tonic",
    price: "12 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Mimosa",
    title_az: "Mimosa",
    price: "13 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Gin & Tonic",
    title_az: "Cin və Tonic",
    price: "11 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Cuba Libre",
    title_az: "Cuba Libre",
    price: "12 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Mojito",
    title_az: "Mojito",
    price: "12 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Tequila Sunrise",
    title_az: "Tequila Sunrise",
    price: "12 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Bloody Mary",
    title_az: "Bloody Mary",
    price: "12 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Blue Lagoon",
    title_az: "Blue Lagoon",
    price: "12 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Sex on the Beach",
    title_az: "Sex on the Beach",
    price: "13 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Pina Colada",
    title_az: "Pina Colada",
    price: "13 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Dry Martini",
    title_az: "Dry Martini",
    price: "12 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Margarita",
    title_az: "Margarita",
    price: "13 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Cosmopolitan",
    title_az: "Cosmopolitan",
    price: "12 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Daiquiri",
    title_az: "Daiquiri",
    price: "12 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Negroni",
    title_az: "Negroni",
    price: "13 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Whiskey Sour",
    title_az: "Whiskey Sour",
    price: "13 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "White Russian",
    title_az: "White Russian",
    price: "12 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Mai-Tai",
    title_az: "Mai-Tai",
    price: "13 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Old Fashioned",
    title_az: "Old Fashioned",
    price: "12 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Godfather",
    title_az: "Godfather",
    price: "12 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Americano",
    title_az: "Americano",
    price: "12 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Amaretto Sour",
    title_az: "Amaretto Sour",
    price: "12 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Espresso Martini",
    title_az: "Espresso Martini",
    price: "13 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Hunter's Sour",
    title_az: "Hunter's Sour",
    price: "12 AZN",
    desc_az: "",
    desc_eng: "",
  },
];

const Jack_Daniels_Cocktails = [
  { nameofArray: "Jack Daniel’s Cocktails" },
  {
    title: "Popping Jack",
    title_az: "Popping Jack",
    price: "14 AZN",
    desc_az: "",
    desc_eng: "Jack Daniel's Tennessee Old Nº7, Mandarin soda",
  },
  {
    title: "Jackbread Collins",
    title_az: "Jackbread Collins",
    price: "14 AZN",
    desc_az: "",
    desc_eng: "Jack Daniel's Tennessee Old Nº7, Fresh Lemon juice, Gingerbread syrup, Tonic water",
  },
  {
    title: "Apple Bergamot Fizz",
    title_az: "Apple Bergamot Fizz",
    price: "14 AZN",
    desc_az: "",
    desc_eng: "Jack Daniel's Tennesse Apple, Fresh lemon juice, Bergamot syrup, Sparkling water",
  },
  {
    title: "Tennessee Spritz",
    title_az: "Tennessee Spritz",
    price: "14 AZN",
    desc_az: "",
    desc_eng: "Jack Daniel's Tennessee Old Nº7, Jack Daniel's Tennessee Honey, Fresh lemon juice, Cinnamon syrup, Mandarin soda",
  },
  {
    title: "Bitter Jack",
    title_az: "Bitter Jack",
    price: "14 AZN",
    desc_az: "",
    desc_eng: "Jack Daniel's Tennessee Old Nº7, Amaretto liqueur, Fresh lemon juice, Angostura bitters",
  },
  {
    title: "Jack Rikki",
    title_az: "Jack Rikki",
    price: "14 AZN",
    desc_az: "",
    desc_eng: "Jack Daniel's Tennessee Honey, Angostura bitters, Tonic water",
  },
  {
    title: "Apple Lynchburg",
    title_az: "Apple Lynchburg",
    price: "14 AZN",
    desc_az: "",
    desc_eng: "Jack Daniel's Tennessee Old Nº7, Jack Daniel's Tennessee Apple, Fresh lemon juice, Sprite",
  },
  {
    title: "Honey Boulevardier",
    title_az: "Honey Boulevardier",
    price: "14 AZN",
    desc_az: "",
    desc_eng: "Jack Daniel's Tennessee Honey, Red sweet vermouth, Campari",
  },
];

const Shots = [
  { nameofArray: "Shots for the Table" },
  {
    title: "Jazzish Shots",
    title_az: "Jazzish Shots",
    price: "20 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Barman’s Brain",
    title_az: "Barman’s Brain",
    price: "24 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "DouDou",
    title_az: "DouDou",
    price: "24 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Snap, Crackle, Drop",
    title_az: "Snap, Crackle, Drop",
    price: "7 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "B-52",
    title_az: "B-52",
    price: "9 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "B-55",
    title_az: "B-55",
    price: "9 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Hunter",
    title_az: "Hunter",
    price: "11 AZN",
    desc_az: "",
    desc_eng: "",
  },
];

export default {
  Whiskey,
  Tequila,
  Aperitif,
  Gin,
  Liqueur,
  Vermouth,
  Vodka,
  Rum,
  BEERS,
  SOFTS,
  Wines,
  Prosecco,
  Coktails,
  Jack_Daniels_Cocktails,
  Shots,
};