// import images from "./Menuimages";

const SALADS_BRUSCHETTAS = [
  { nameofArray: "Salads & Bruschettas" },
  {
    title: "Smoked Salmon Salad",
    title_az: "Hisə Verilmiş Qızıl Balıq Salatı",
    price: "15.8 AZN",
    desc_az: "Hisə verilmiş qızıl balıq, göyərtilər, limon sousu, çerri pomidoru, portağal",
    desc_eng: "Smoked salmon, mix salad, mix cheese, lemon sauce, cherry tomato, orange",
  },
  {
    title: "Tuna Salad",
    title_az: "Tuna Salatı",
    price: "12 AZN",
    desc_az: "Tuna balığı, qaynadılmış yumurta, göyərtilər, qarğıdalı, zeytun, çerri pomidoru",
    desc_eng: "Tuna, boiled egg, mix salad, corn, olive, cherry tomato",
  },
  {
    title: "Vegetarian Salad",
    title_az: "Vegeterian Salatı",
    price: "10.8 AZN",
    desc_az: "Avokado, xiyar, çerri pomidoru, qarğıdalı, zeytun, limon sousu, ağ pendir, göyərtilər",
    desc_eng: "Avocado, cucumber, cherry tomato, corn, olive, lemon sauce, white cheese, mix salad",
  },
  {
    title: "Caesar Salad",
    title_az: "Sezar Salatı",
    price: "12.80 / 14.80 AZN",
    desc_az: "Seazar sousu, aysberq, parmezan pendiri, çerri pomidoru, suxarı, toyuq filesi və ya krevet ilə",
    desc_eng: "Caesar sauce, iceberg, parmesan, cherry tomato, croutons with chicken fillet or prawn",
  },
  {
    title: "Beef Salad",
    title_az: "Can Əti Salatı",
    price: "14.8 AZN",
    desc_az: "Can əti, göyərtilər, limon sousu, çerri pomidoru, qoz, qırmızı lobya",
    desc_eng: "Beef tenderloin, mix salad, lemon sauce, cherry tomato, walnut, red kidney beans",
  },
  {
    title: "Chicken Popcorn Salad",
    title_az: "Toyuq Popkorn Salatı",
    price: "12.8 AZN",
    desc_az: "Toyuq popkorn, avokado, çerri pomidoru, qarğıdalı, göyərtilər, popkorn sousu",
    desc_eng: "Chicken popcorn, avocado, cherry tomato, corn, mix salad, popcorn sauce",
  },
  {
    title: "Bruschetta Salmon",
    title_az: "Qızıl balıq Brusketta",
    price: "16 AZN",
    desc_az: "Çiabatta çörəyi, hisə verilmiş qızıl balıq, çerri pomidoru, qırmızı soğan, kapers",
    desc_eng: "Ciabatta bread, smoked salmon, cherry tomato, red onion, capers",
  },
  {
    title: "Bruschetta Tomato",
    title_az: "Pomidorlu Brusketta",
    price: "12 AZN",
    desc_az: "Çiabatta çörəyi, pomidor, balzamik sous, kəklikotu",
    desc_eng: "Ciabatta bread, tomato, balsamic sauce, oregano",
  },
  {
    title: "Bruschetta Chicken",
    title_az: "Toyuqlu Brusketta",
    price: "14 AZN",
    desc_az: "Çiabatta çörəyi, hisə verilmiş toyuq, balzamik sous, qarğıdalı",
    desc_eng: "Ciabatta bread, smoked chicken, balsamic sauce, corn",
  },
  {
    title: "Bruschetta Beef",
    title_az: "Ətli Brusketta",
    price: "15 AZN",
    desc_az: "Çiabatta çörəyi, hisə verilmiş mal əti, pomidor, kapers",
    desc_eng: "Ciabatta bread, smoked beef slices, tomato, capers",
  },
];

const BURGERS_SANDWICHES = [
  { nameofArray: "Burgers & Sandwiches" },
  {
    title: "Beef Burger",
    title_az: "Dana Burger",
    price: "13.9 AZN",
    desc_az: "Dana əti, xüsusi sous, çedar, karamelizə qırmızı soğan, turşu xiyar, pomidor, kahı, kartof fri ilə",
    desc_eng: "Beef, special sauce, cheddar cheese, caramelized red onion, pickle, tomato, lettuce, with french fries",
  },
  {
    title: "Cheese Burger",
    title_az: "Çizburger",
    price: "14.9 AZN",
    desc_az: "Dana əti, çedar sousu, çedar dilimi, karamelizə qırmızı soğan, turşu xiyar, pomidor, kahı kartof fri ilə",
    desc_eng: "Beef, cheddar sauce, cheddar slice, caramelized red onion, pickle, tomato, lettuce, with french fries",
  },
  {
    title: "ETUD Burger",
    title_az: "ETUD Burger",
    price: "16.9 AZN",
    desc_az: "Dana əti, bekon, çedar pendiri, xüsusi sous, karamelizə qırmızı soğan, turşu xiyar, pomidor, kahı kartof fri ilə",
    desc_eng: "Beef, bacon, cheddar cheese, special sauce, caramelized red onion, pickle, tomato, lettuce, with french fries",
    imgUrl: "",
  },
  {
    title: "Chicken Burger",
    title_az: "Toyuq Burger",
    price: "12.9 AZN",
    desc_az: "Toyuq, xüsusi sous, çedar pendiri, turşu xiyar, pomidor, kahı, kartof fri ilə",
    desc_eng: "Chicken, special sauce, cheddar cheese, pickle, tomato, lettuce, with french fries",
  },
  {
    title: "Mushroom Burger",
    title_az: "Göbələk Burger",
    price: "14.9 AZN",
    desc_az: "Dana əti, göbələk sousu, kahı, turşu xiyar, kartof fri ilə",
    desc_eng: "Beef, mushroom sauce, lettuce, cucumber pickle, with french fries",
  },
  {
    title: "Vegetarian Burger",
    title_az: "Vegetarian Burger",
    price: "12 AZN",
    desc_az: "Vegetarian köftə, xüsusi sous, çedar pendiri, karamelizə qırmızı soğan, turşu xiyar, pomidor, kahı, kartof fri ilə",
    desc_eng: "Veggie patty, special sauce, cheddar cheese, caramelized red onion, pickle, tomato, lettuce, with french fries",
  },
  {
    title: "Mini Burgers",
    title_az: "Kiçik Burgerlər",
    price: "14.9 AZN",
    desc_az: "İki kiçik dana burger, tartar sousu, mozzarella pendiri, turşu xiyar, kahı, kartof fri ilə",
    desc_eng: "Two mini beef burgers, tartar sauce, mozzarella cheese, pickle, lettuce, with french fries",
  },
  {
    title: "Mexican Burger",
    title_az: "Meksikan Burger",
    price: "14.9 AZN",
    desc_az: "Dana əti, xüsusi sous, acılı meksikan sousu, turşu xiyar, pomidor, kahı, kartof fri ilə",
    desc_eng: "Beef, special sauce, spicy mexican sauce, pickle, tomato, lettuce, with french fries",
  },
  {
    title: "Steak Burger",
    title_az: "Steyk Burger",
    price: "15.9 AZN",
    desc_az: "Can əti steyk, turşu xiyar, pomidor, kahı, kartof fri ilə",
    desc_eng: "Beef tenderloin steak, pickle, tomato, lettuce, with french fries",
  },
  {
    title: "Club Sandwich",
    title_az: "Klub Sendviç",
    price: "12 AZN",
    desc_az: "Toyuq filesi, yumurta, mozzarella pendiri, pomidor, kahı, turşu xiyar, kartof fri ilə",
    desc_eng: "Chicken fillet, egg, mozzarella cheese, tomato, lettuce, pickle, with french fries",
  },
  {
    title: "Chicken Sandwich",
    title_az: "Toyuq Sendviç",
    price: "11.9 AZN",
    desc_az: "Toyuq filesi, mozzarella, pomidor, turşu xiyar, kahı",
    desc_eng: "Chicken fillet, mozzarella, tomato, pickle, lettuce",
  },
  {
    title: "Salmon Sandwich",
    title_az: "Qızıl Balıq Sendviç",
    price: "14.9 AZN",
    desc_az: "Hisə verilmiş qızıl balıq, pesto sousu, kahı",
    desc_eng: "Smoked salmon, pesto sauce, lettuce",
  },
  {
    title: "Caesar Roll",
    title_az: "Sezar Roll",
    price: "11.9 AZN",
    desc_az: "Tortilla lavaşı, sezar sous, toyuq filesi, parmezan, pomidor, aysberq, kartof fri ilə",
    desc_eng: "Tortilla, Caesar sauce, chicken fillet, parmesan, tomato, iceberg, with french fries",
  },
  {
    title: "Steak Sandwich",
    title_az: "Steyk Sendviç",
    price: "13.9 AZN",
    desc_az: "Can əti steyk, mozzarella pendiri, turşu xiyar, pomidor, kahı, tartar sousu",
    desc_eng: "Beef tenderloin steak, mozzarella cheese, pickle, tomato, lettuce, tartar sauce",
  },
  {
    title: "Chicken Pesto Sandwich",
    title_az: "Pesto Souslu Toyuq Sendviç",
    price: "12.9 AZN",
    desc_az: "Toyuq filesi, pesto sousu, mozzarella, pomidor",
    desc_eng: "Chicken fillet, pesto sauce, mozzarella, tomato",
  },
];

const Snacks_Sets = [
  { nameofArray: "Snack Sets" },
  {
    title: "ETUD's Special Set",
    title_az: "ETUD Özel Set",
    price: "36 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Sausage Board",
    title_az: "Sosis Assorti",
    price: "17 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Cheese Board",
    title_az: "Pendir Assorti",
    price: "22 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Meat Board",
    title_az: "Ət Assorti",
    price: "24 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Fruit Plate",
    title_az: "Meyvə Boşqabı",
    price: "16 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Nachos/Minced Meat",
    title_az: "Naços/Qiyməli",
    price: "14.00 / 17.00 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Quesadilla",
    title_az: "Kesadila",
    price: "12 AZN",
    desc_az: "Tortilla lavaşı, can əti, qarışıq pendirlər, xüsusi sous",
    desc_eng: "Tortilla, beef tenderloin, cheese mix, special sauce",
  },
  {
    title: "Panko Prawns",
    title_az: "Panko Krevet",
    price: "12 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Panko Calamari",
    title_az: "Panko Kalmar",
    price: "12 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Fish & Chips",
    title_az: "Balıq və Kartof Dilimləri",
    price: "12 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Chicken Schnitzel",
    title_az: "Toyuq Şnitzel",
    price: "12 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Chicken Pate",
    title_az: "Toyuq Paştet",
    price: "10 AZN",
    desc_az: "Toyuq Paşteti, baget çörək, kərə yağı",
    desc_eng: "Chicken Pâté, baguette bread, butter",
  },
  {
    title: "Mozzarella Sticks",
    title_az: "Mozzarella Çubuqları",
    price: "8 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Cheese Balls",
    title_az: "Pendir Topları",
    price: "8 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Nuggets",
    title_az: "Naqets",
    price: "8 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Chicken Popcorn",
    title_az: "Toyuq Popkorn",
    price: "8 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "BBQ Chicken Wings",
    title_az: "BBQ Toyuq Qanadları",
    price: "8 AZN",
    desc_az: "BBQ sousunda toyuq qanadları",
    desc_eng: "Chicken wings in BBQ sauce",
  },
  {
    title: "Chicken Wings",
    title_az: "Toyuq Qanadları",
    price: "8 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Onion Rings",
    title_az: "Soğan Halqaları",
    price: "6 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Pistachios",
    title_az: "Püstə",
    price: "7 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "French Fries",
    title_az: "Kartof Fri",
    price: "5 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Cheese Fries",
    title_az: "Pendirli Kartof Fri",
    price: "6 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Potato Wedges",
    title_az: "Kartof Dilimləri",
    price: "5 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Peanuts",
    title_az: "Duzlu Yerfıstıqları",
    price: "5 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Fried Dushbara",
    title_az: "Qızardılmış Düşbərə",
    price: "5 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Fried String Cheese",
    title_az: "Qızardılmış Saçaqlı Pendir",
    price: "5 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "String Cheese",
    title_az: "Saçaqlı Pendir",
    price: "5 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Chips",
    title_az: "Çips",
    price: "5 AZN",
    desc_az: "",
    desc_eng: "",
  },
  {
    title: "Olive",
    title_az: "Zeytun",
    price: "6 AZN",
    desc_az: "",
    desc_eng: "",
  },
];

const New = [
  { nameofArray: "New Items" },
  {
    title: "Lazanya / Lasagna",
    title_az: "YENİ Lazanya / Lasagna",
    price: "15 AZN",
    desc_az: "Bolognese bəşəmel sousu, lasagna xəmiri",
    desc_eng: "Bolognese Béchamel sauce, lasagna dough",
  },
  {
    title: "Chicken Pate",
    title_az: "Toyuq Paştet",
    price: "15 AZN",
    desc_az: "Pastet bağet çörək, karabəf, toyuq əti, peynir, xüsusi sous",
    desc_eng: "pastry baguette bread, beef, chicken meat, cheese mix, special sauce",
  },
  {
    title: "BBQ Wings",
    title_az: "BBQ Kanatlar",
    price: "15 AZN",
    desc_az: "BBQ sousunda toyuq kanatları, peynir, xüsusi sous",
    desc_eng: "BBQ sauce chicken wings, cheese mix, special sauce",
  },
];

export default { SALADS_BRUSCHETTAS, BURGERS_SANDWICHES, Snacks_Sets, New };